version: '3.9'
services:

  nestjs_server:
    image: 'nestjs-image:latest' 
    container_name: nestjs_server
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgreSQL_DB
      - POSTGRES_DB=Your_Little_Notes_DB
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432

  postgres_db:
    image: 'postgres:latest'
    container_name: postgres_db
    restart: always
    environment:
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - '5432:5432' 
