version: '3.9'
services:

  nestjs_server:
    image: 'nestjs-image:latest' 
    container_name: nestjs_server
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db

  postgres_db:
    image: 'postgres:latest'
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER 
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD  
      POSTGRES_DB: process.env.POSTGRES_DB  
    ports:
      - '5432:5432' 
